# Generated by Django 3.2.3 on 2021-05-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
