# Generated by Django 3.2.3 on 2021-05-23 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyg', '0002_auto_20210520_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=50)),
                ('discount_per', models.IntegerField()),
                ('valid_from', models.DateField()),
                ('valid_till', models.DateField()),
                ('limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brief_desc', models.TextField(null=True)),
                ('course_thumbnail', models.ImageField(blank=True, null=True, upload_to='Course Thumbnail')),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0, null=True)),
                ('discount', models.FloatField(default=0, null=True)),
                ('total', models.FloatField(default=0, null=True)),
                ('course_pay', models.CharField(choices=[('Subscription', 'Subscription'), ('One-Time-Pay', 'One-Time-Pay')], max_length=200)),
                ('publish', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='gyg.category')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('next_payment_date', models.DateTimeField()),
                ('last_payment_date', models.DateTimeField()),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gyg.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(blank=True, related_name='user_courses', to='gyg.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_every', models.CharField(choices=[('1 MONTH', '1 MONTH'), ('2 MONTHS', '2 MONTHS'), ('3 MONTHS', '3 MONTHS')], max_length=100)),
                ('_for', models.CharField(choices=[('3 Months', '3 Months'), ('6 Months', '6 Months'), ('1 Year', '1 Year')], max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyg.course')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('coupon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gyg.couponcode')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyg.course')),
            ],
        ),
        migrations.AddField(
            model_name='couponcode',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyg.course'),
        ),
    ]
