# Generated by Django 3.2.3 on 2021-05-24 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyg', '0004_course_include_file_topic_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_include',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gyg.course'),
        ),
    ]
