# Generated by Django 3.2.3 on 2021-05-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyg', '0005_course_include_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDoubtSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=5000)),
                ('thumbnail', models.ImageField(upload_to='Lives')),
                ('from_time', models.TimeField(null=True)),
                ('to_time', models.TimeField(null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_doubts', to='gyg.course')),
            ],
        ),
    ]
