# Generated by Django 3.2.3 on 2021-05-29 11:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyg', '0006_livedoubtsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ques_img', models.ImageField(blank=True, null=True, upload_to='Question')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_questions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gyg.topic')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_img', models.ImageField(blank=True, null=True, upload_to='Answers')),
                ('answer', models.TextField()),
                ('answer_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL)),
                ('answer_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gyg.questions')),
            ],
        ),
    ]
