# Generated by Django 3.2.3 on 2021-05-30 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyg', '0007_answer_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='_every',
            new_name='every',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='_for',
            new_name='till',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
